### ISSUE TITLE
A fix for parsing error on URIs 

### ISSUE THREAD

**Issue by shawnbohn-pnnl** [csirtgadgets/csirtg-indicator-v3#8]
I identified a fix that I would like you to consider:

If you run "csirtg-fm -r rules/openphish.yml -d -f urls", it will show that it cannot parse the results.  I tracked it down to the fact that the csirtg_re module assumes the RE_URI_SCHEMES require ://, which it doesn't, at least in this case.  However, It wasn't sufficient to just make that change.  I also had to make the change in csirtg_indicator/utils/__init__.py, to deal with the method is_url().  In that module it recast the url to hostname and following functions fail because of this.  Below are modifications I made to the two files, let me know if you concur with the changes.  Please update them and we would love to get a new update to your system.

**CHANGE IN FIRST FILE:**

	diff --git a/csirtg_re/__init__.py b/csirtg_re/__init__.py
	index aa40839..2886038 100644
	--- a/csirtg_re/__init__.py
	+++ b/csirtg_re/__init__.py
	@@ -16,7 +16,7 @@ RE_IPV6 = re.compile(r'(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,
	 #RE_FQDN = re.compile('^((?!-))(xn--)?[a-z0-9][a-z0-9-_\.]{0,61}[a-z0-9]{0,1}\.(xn--)?([a-z0-9\-]{1,61}|[a-z0-9-]{1,30}\.[a-z]{2,})$')
	 # http://stackoverflow.com/questions/14402407/maximum-length-of-a-domain-name-without-the-http-www-com-parts
	 RE_FQDN = re.compile(r'^((?!-))(xn--)?[a-zA-Z0-9][a-zA-Z0-9-_\.]{0,245}[a-zA-Z0-9]{0,1}\.(xn--)?([a-zA-Z0-9\-]{1,61}|[a-zA-Z0-9-]{1,30}\.[a-z]{2,})$')
	-RE_URI_SCHEMES = re.compile(r'^(https?|ftp)://')
	+RE_URI_SCHEMES = re.compile(r'^(https?|ftp)')
	 RE_EMAIL = re.compile(r'^[_a-zA-Z0-9-\!\#\$\%\&\'\*\+\-\/\=\?\^\_\`\{\|\}\~]+(\.[_a-zA-Z0-9-\!\#\$\%\&\'\*\+\-\/\=\?\^\_\`\{\|\}\~]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*(\.[a-zA-Z]{2,8})$')
	 RE_ASN = re.compile(r'^(AS|as)[0-9]{1,6}$')

 **CHANGE IN SECOND FILE:**

	diff --git a/csirtg_indicator/utils/__init__.py b/csirtg_indicator/utils/__init__.py
	index 662bf42..3bfa8b4 100644
	--- a/csirtg_indicator/utils/__init__.py
	+++ b/csirtg_indicator/utils/__init__.py
	@@ -59,13 +59,11 @@ def is_url(s):
     if not re.match(RE_URI_SCHEMES, str(u.scheme)):
         return

	-    u = u.hostname
	-
	-    if is_ip(u) or is_fqdn(u):
	+    if is_ip(u.hostname) or is_fqdn(u.hostname):
			 return True

	-    if ':' in u:  # 192.168.1.1:81
	-        u1 = u.split(':')[0]
	+    if ':' in u.hostname:  # 192.168.1.1:81
	+        u1 = u.hostname.split(':')[0]
			 if is_ipv4(u1) or is_fqdn(u1):
				 return True

**Comment by wesyoung** [comment]
send a pr- happy to merge!
